spring.application.name=restaurant

# Core 
spring.profiles.active=h2

#base endpoint configs
api-endpoint = api/v1

#jwt tokens
jwt-secret= ${JWT_SECRET}

# Docker
spring.docker.compose.enabled=false